import { readFileSync, writeFileSync } from 'fs';
const f = 'C:/Projects/Claude proj/yotamquesT/src/game/scenes/MazeScene.js';
let s = readFileSync(f, 'utf8');

// ── Wire _startAmbience in create() after _initAudio() ───────────────────────
const WIRE_MARKER = '    // Particles + audio\n    this._initParticles();\n    this._initAudio();';
if (!s.includes(WIRE_MARKER)) { console.error('WIRE_MARKER not found'); process.exit(1); }
s = s.replace(
  WIRE_MARKER,
  '    // Particles + audio\n    this._initParticles();\n    this._initAudio();\n    this._startAmbience();'
);
console.log('✓ _startAmbience wired');

// ── Insert new methods before atmospheric lighting section ────────────────────
const INSERT_BEFORE = '  // ── atmospheric lighting ─────────────────────────────────────────────────────';
if (!s.includes(INSERT_BEFORE)) { console.error('INSERT_BEFORE not found'); process.exit(1); }

const NEW_METHODS = [
  `  // ── combo system ──────────────────────────────────────────────────────────────`,
  `  _trackCombo() {`,
  `    const now = this.time.now;`,
  `    this._comboHistory = (this._comboHistory ?? []).filter(t => now - t < 2000);`,
  `    this._comboHistory.push(now);`,
  `    if (this._comboHistory.length >= 3) {`,
  `      this._showCombo(this._comboHistory.length);`,
  `      this._comboHistory = [];`,
  `    }`,
  `  }`,
  ``,
  `  _showCombo(n) {`,
  `    const cx = this.cameras.main.width / 2;`,
  `    const txt = this.add.text(cx, this.cameras.main.height / 2 - 60,`,
  `      'COMBO x' + n + '! ⚡',`,
  `      {`,
  `        fontFamily: 'Courier New, monospace', fontSize: '22px', color: '#00ccff',`,
  `        stroke: '#000000', strokeThickness: 4,`,
  `        shadow: { offsetX: 0, offsetY: 0, color: '#00aaff', blur: 18, fill: true },`,
  `      }`,
  `    ).setOrigin(0.5).setDepth(202).setScrollFactor(0).setAlpha(0).setScale(0.5);`,
  `    this.tweens.add({`,
  `      targets: txt, alpha: 1, scaleX: 1, scaleY: 1,`,
  `      duration: 200, ease: 'Back.easeOut',`,
  `      onComplete: () => {`,
  `        this.time.delayedCall(800, () => {`,
  `          this.tweens.add({ targets: txt, alpha: 0, y: txt.y - 20, duration: 300,`,
  `            onComplete: () => txt.destroy() });`,
  `        });`,
  `      },`,
  `    });`,
  `    this._playSound('correct');`,
  `  }`,
  ``,
  `  // ── ambient atmosphere (Part 2E) ──────────────────────────────────────────────`,
  `  // Randomly triggers a subtle effect every 10-15 s. Never interrupts gameplay.`,
  `  _startAmbience() {`,
  `    const scheduleNext = () => {`,
  `      const delay = Phaser.Math.Between(10000, 15000);`,
  `      this.time.delayedCall(delay, () => {`,
  `        if (!this.scene.isActive()) return;`,
  `        this._doAmbientEffect();`,
  `        scheduleNext();`,
  `      });`,
  `    };`,
  `    scheduleNext();`,
  `  }`,
  ``,
  `  _doAmbientEffect() {`,
  `    const pick = Phaser.Math.Between(0, 2);`,
  `    if (pick === 0) this._ambientRadio();`,
  `    else if (pick === 1) this._ambientWallBlink();`,
  `    else this._ambientFloorSpark();`,
  `  }`,
  ``,
  `  _ambientRadio() {`,
  `    this._playSound('radio_static');`,
  `    // Brief white-noise visual: rapid flicker on a tiny screen overlay`,
  `    const flicker = this.add.rectangle(`,
  `      this.cameras.main.width / 2, this.cameras.main.height / 2,`,
  `      this.cameras.main.width, this.cameras.main.height,`,
  `      0xffffff, 0.03`,
  `    ).setDepth(495).setScrollFactor(0);`,
  `    let ticks = 0;`,
  `    const iv = this.time.addEvent({`,
  `      delay: 50, repeat: 6,`,
  `      callback: () => {`,
  `        flicker.setAlpha(ticks % 2 === 0 ? 0.04 : 0);`,
  `        ticks++;`,
  `        if (ticks >= 6) { flicker.destroy(); iv.destroy(); }`,
  `      },`,
  `    });`,
  `  }`,
  ``,
  `  _ambientWallBlink() {`,
  `    // Flash a small neon-blue square over a random wall tile near the player`,
  `    const pr = this._lastTR ?? 17, pc = this._lastTC ?? 9;`,
  `    const candidates = [];`,
  `    for (let dr = -4; dr <= 4; dr++) {`,
  `      for (let dc = -4; dc <= 4; dc++) {`,
  `        const r = pr + dr, c = pc + dc;`,
  `        if (r < 0 || r >= ROWS || c < 0 || c >= COLS) continue;`,
  `        if (this.map[r][c] === WALL) candidates.push([r, c]);`,
  `      }`,
  `    }`,
  `    if (!candidates.length) return;`,
  `    const [r, c] = candidates[Phaser.Math.Between(0, candidates.length - 1)];`,
  `    const wx = c * TILE + TILE / 2, wy = r * TILE + TILE / 2;`,
  `    const rect = this.add.rectangle(wx, wy, TILE - 4, TILE - 4, 0x0044ff, 0.0)`,
  `      .setDepth(4);`,
  `    this.tweens.add({`,
  `      targets: rect, alpha: 0.18,`,
  `      yoyo: true, duration: 120, repeat: 2,`,
  `      onComplete: () => rect.destroy(),`,
  `    });`,
  `  }`,
  ``,
  `  _ambientFloorSpark() {`,
  `    // Small spark burst at a random floor tile near player`,
  `    const pr = this._lastTR ?? 17, pc = this._lastTC ?? 9;`,
  `    const candidates = [];`,
  `    for (let dr = -3; dr <= 3; dr++) {`,
  `      for (let dc = -3; dc <= 3; dc++) {`,
  `        const r = pr + dr, c = pc + dc;`,
  `        if (r < 0 || r >= ROWS || c < 0 || c >= COLS) continue;`,
  `        if (this.map[r][c] >= FLOOR) candidates.push([r, c]);`,
  `      }`,
  `    }`,
  `    if (!candidates.length) return;`,
  `    const [r, c] = candidates[Phaser.Math.Between(0, candidates.length - 1)];`,
  `    const wx = c * TILE + Phaser.Math.Between(4, TILE - 4);`,
  `    const wy = r * TILE + Phaser.Math.Between(4, TILE - 4);`,
  `    const emitter = this.add.particles(wx, wy, 'particle_spark', {`,
  `      speed: { min: 20, max: 55 }, angle: { min: 0, max: 360 },`,
  `      scale: { start: 0.6, end: 0 }, lifespan: 220,`,
  `      tint: [0x00aaff, 0x00ffcc], emitting: false,`,
  `    }).setDepth(8);`,
  `    emitter.explode(Phaser.Math.Between(2, 4));`,
  `    this.time.delayedCall(300, () => { if (emitter?.active) emitter.destroy(); });`,
  `  }`,
  ``,
  ``,
].join('\n');

s = s.replace(INSERT_BEFORE, NEW_METHODS + INSERT_BEFORE);
console.log('✓ combo + ambience methods inserted');

// ── Add radio_static case to _playSound ───────────────────────────────────────
s = s.replace(
  `      case 'mine': {`,
  [
    `      case 'radio_static': {`,
    `        // Short white-noise burst via rapid frequency modulation`,
    `        osc.type = 'sawtooth';`,
    `        osc.frequency.setValueAtTime(800, now);`,
    `        osc.frequency.setValueAtTime(200, now + 0.05);`,
    `        osc.frequency.setValueAtTime(1200, now + 0.12);`,
    `        osc.frequency.setValueAtTime(400, now + 0.22);`,
    `        gain.gain.setValueAtTime(0.04, now);`,
    `        gain.gain.exponentialRampToValueAtTime(0.001, now + 0.30);`,
    `        osc.start(now); osc.stop(now + 0.30);`,
    `        break;`,
    `      }`,
    `      case 'mine': {`,
  ].join('\n')
);
console.log('✓ radio_static sound added');

writeFileSync(f, s, 'utf8');
console.log('All 2E edits saved.');
